version: '3'

volumes:
  pg_data:
  static:
  django_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: diaphanous/foodgram_backend
    env_file: .env
    volumes:
      - django_static:/app/collected_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: diaphanous/foodgram_frontend
    volumes:
      - static:/app/build/
    depends_on:
      - db


  gateway:
    image: diaphanous/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - django_static:/staticfiles/build/static
      - media:/app/media/
    depends_on:
      - backend
      - frontend
