version: '3'

volumes:
  pg_data:
  static:
  media:
  django_static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - django_static:/app/collected_static
      - media:/app/media/
    depends_on:
      - db


  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/app/build/
    depends_on:
      - db

  gateway:
    build: ./infra/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - django_static:/staticfiles/build/static
      - media:/app/media/
    depends_on:
      - backend
      - frontend
