# Generated by Django 4.2.13 on 2024-10-09 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(700), django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов в данном рецепте'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(700, 'Кол-во не может быть более 700'), django.core.validators.MinValueValidator(1, 'Кол-во не может быть меньше 1')], verbose_name='Количество ингредиентов в данном рецепте'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientinrecipe',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
