# Generated by Django 3.2.25 on 2024-09-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240929_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
